FROM node:18-alpine

WORKDIR /app

# Установка только необходимых зависимостей
COPY package.json ./
RUN yarn add prisma @prisma/client --save-dev

# Копирование schema.prisma
COPY prisma ./prisma

# Генерация Prisma Client
RUN npx prisma generate

# Команда для запуска Prisma Studio
CMD ["npx", "prisma", "studio", "--port", "5555"]