version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./prisma:/app/prisma
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json
    environment:
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - PRISMA_CLI_QUERY_ENGINE_TYPE=library
      - DATABASE_URL=file:/app/data/database.db
      - DATABASE_PATH=/app/data/database.db
    ports:
      - '3000:3000'
    command:
      - sh
      - -c
      - |
        mkdir -p /app/data && chmod -R 777 /app/data
        echo 'Синхронизация схемы с базой...'
        npx prisma db push
        echo 'Схема синхронизирована'
        npm run start:prod

volumes:
  data:
