version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json
    environment:
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - PRISMA_CLI_QUERY_ENGINE_TYPE=library
    ports:
      - '3000:3000'
volumes:
  data:
